### PR TITLE
Add Rubocop to CircleCI builds

### PR DESCRIPTION
**Pull request by pelargir**
Do we want to enable Rubocop as a PR check in GitHub as well?

### CODE REVIEW

**Comment by mamhoff** [comment]
Good idea - but then we'd probably want the check to pass. I'd happily accept a PR that runs `rubocop -a` and then fixes the remaining few issues.

**Comment by pelargir** [comment]
@mamhoff done!

**Comment by pelargir** [comment]
@mamhoff does this look good now?

**Review by mamhoff — APPROVED** [review]
Yeah, let's do this!

**Pull request merged**
