### PR TITLE
Add `Physical::Pallet` class

### PR DESCRIPTION
**Pull request by pelargir**
This allows `Physical::Package` instances to represent pallets when their container is a `Physical::Pallet` instance. A pallet has max weight and dimensions (representing the length, width, and height of the pallet itself) but no inner dimensions since items are placed on top, not inside.

### CODE REVIEW

**Review by mamhoff — APPROVED** [review]
Nice :)

**Comment by pelargir** [comment]
@mamhoff the build is failing. CircleCI can't check out the code. Looks like an outdated SSH key to me. Can you help?

**Comment by mamhoff** [comment]
I'll fix it tomorrow, I've cycled a few keys recently

**Comment by mamhoff** [comment]
OK TIL CircleCI needs a deploy key to be able to checkout public repositories.

**Pull request merged**
